### ISSUE TITLE
dont work on ubuntu 14.04

### ISSUE THREAD

**Issue by abbas-h** [selwin/python-user-agents#23]
i install ua-parser and user-agents on ubuntu via pip ...

but when i run python script always get me error 

ua = parse('Mozilla/5.0 (iPhone; CPU iPhone OS 5_1 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/9B179 Safari/7534.48.3') 
File "/usr/local/lib/python2.7/dist-packages/user_agents/parsers.py", line 205, in parse
return UserAgent(user_agent_string)
File "/usr/local/lib/python2.7/dist-packages/user_agents/parsers.py", line 113, in __init__
self.device = parse_device(**ua_dict['device'])
TypeError: parse_device() got an unexpected keyword argument 'brand'

**Comment by selwin** [comment]
You should install all the latest libraries from PyPI with this:
```
pip install pyyaml ua-parser user-agents
```

**Comment by jjmalina** [comment]
Getting the same issue now in my application tests

```
self = <user_agents.parsers.UserAgent object at 0x7ff2fe523090>
user_agent_string = 'Mozilla/5.0 (Windows NT 6.3; WOW64; result:34.0) Gecko/20100101 Firefox/34.0'
    def __init__(self, user_agent_string):
        ua_dict = user_agent_parser.Parse(user_agent_string)
        self.ua_string = user_agent_string
        self.os = parse_operating_system(**ua_dict['os'])
        self.browser = parse_browser(**ua_dict['user_agent'])
>       self.device = parse_device(**ua_dict['device'])
E       TypeError: parse_device() got an unexpected keyword argument 'brand'
```

I have PyYAML-3.11, ua-parser-0.4.0 and user-agents-0.3.2 installed.

**Comment by tulpn** [comment]
I am getting the same issue, as JJMalina, I have followed the instructions in the README and I am running PIP. I do get it working though, __if I don't treat ua_dict in parser.py as a kwargs__ and remove ** from it it, it works. However, I won't consider this a fix. However, it then returns for the device:

`{'brand': None, 'model': None, 'family': 'Other'}`

My user agent is __'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36'__

**uname -a**: `Linux debian-gohan 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt7-1 (2015-03-01) x86_64 GNU/Linux`

It is **run in a Virtual Machine.**

**Comment by selwin** [comment]
A new version of `python-user-agents` that works with `ua-parser` 0.4.0 is now up on PyPi, please upgrade to the newest version. Sorry about that.

**Comment by tulpn** [comment]
Works like a charm. Tested with the django module. Thank you for the quick fix!

**Comment by jjmalina** [comment]
@selwin can I suggest putting a version on `ua-parser` in setup.py so that if a new version comes out with breaking changes it won't break `python-user-agents`, what do you think? i already did that in my requirements.txt but it would be nice to let `python-user-agents` take care of it
